### ISSUE TITLE
Main Routes

### ISSUE THREAD

**Issue by paulogarithm** [JDK-Tek/AREA#64]
implement a route to create a new area, and one to get tokens

## `POST /api/area`
- asks for token
- have the action + actions parametters
- have the reaction + reaction parametters

## `GET /api/oauth/[service name]`
returns the oauth link with the redirect link you gave

## `POST /api/oauth/[service name]`
sets the "code" or "token" to something

## SubTask
- [ ] area token contains userid
- [ ] area token contains authantification method

## Tasks
- [x] (area/new) when this port is trigger fill the database
- [x] (area/new) post to the good microservice
- [ ] (get oauth) call the microservice
- [ ] (get oauth) return the good oauth link
- [ ] (post oauth) call the microservice
- [ ] (post oauth) store token in database
- [ ] (post oauth) able to connect using oauth (get an area token)
